### ISSUE TITLE
config Script TODO

### ISSUE THREAD

**Issue by darkdrgn2k** [tomeshnet/prototype-cjdns-pi#130]
- [x] Create mesh.conf on startup
- [x] Migrate ap configuration questions during install
- [x] Remove hostapd.conf configuration
- [ ] Default config to 80211s
- [x] Add check if interface has 80211s support
- [ ] Reconfigure interface after config completion
- [ ] Fix boot pause waiting for interface
- [x] Kill network manager once and for all (move to systemd)
- [ ] swap script to migrate configs between mac
- [ ] add cjdns gateway pinning
- [ ] add eth support for exit/enter node
- [x] remove hostapd in /etc/systemd/system to allow hostapd@ to work
- [x] replace hostapd@ startup script to one that checks if it should be a hostapd
- [x] really.. kill network-manager service
- [x] correct issues with hostapd not starting correctly
